# Generated by Django 4.2 on 2023-04-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='time_create',
            field=models.TextField(default='12-04-2023 16:12:21'),
        ),
    ]
